services:
  jukebox:
    build:
      context: .
      dockerfile: docker/Dockerfile
      network: host
    container_name: jukebox
    restart: unless-stopped
    env_file:
      - .env.urls
      - /mnt/config/secrets/jukebox/env
      - /mnt/config/secrets/bash/bash_lidarr-api-key.env
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - gluetun_network
networks:
  gluetun_network:
    external: true
